version: "3.9"
services:
  dev:
    image: linjieli222/videocap_torch1.7:fairscale
    working_dir: /videocap
    volumes:
      - .:/videocap
      - /data/dataset/SwinBERT-Refactoring/datasets:/videocap/datasets
      - /data/dataset/SwinBERT-Refactoring/predictions:/videocap/predictions
      - /data/dataset/SwinBERT-Refactoring/models:/videocap/models
      - /data:/data
    environment:
      - TZ=Asis/Seoul
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    stdin_open: true
    command: bash -c "source /videocap/setup.sh && bash"